config/routes.rb
Rails.application.routes.draw do
  
  # Set Root Directory #
  root 'static_pages#home'
  
  # Set Static Pages Directories #
  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    # Display Full Title 
    def full_title(page_title = '')
        title = "SocialH3x"
        if page_title.empty?
            title 
        else
            page_title + " | " + title 
        end
    end
    
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        <%= link_to 'SocialH3x', root_path %> is built upon the <%= link_to image_tag('rails.png', size: '25x25'), 'http://www.rubyonrails.org', target: '_blank' %> Framework! 
        By; <%= link_to 'Aubrey Love', 'https://www.linkedin.com/in/aubreywlove/', target: '_blank' %>
    </small>
    <nav>
        <ul>
            <li><%= link_to 'About', about_path %></li>
            <li><%= link_to 'Contact', contact_path %></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="topnav" id="myTopnav">
    <% if current_page?(controller: 'static_pages', action: 'home') %>
        <%= link_to 'Home', root_path, class: 'active' %>
        <%= link_to 'About', about_path %>
        <%= link_to 'Help', help_path %>
        <%= link_to 'Contact', contact_path %>
    <% end %>
    
    <% if current_page?(controller: 'static_pages', action: 'about') %>
        <%= link_to 'Home', root_path %>
        <%= link_to 'About', about_path, class: 'active' %>
        <%= link_to 'Help', help_path %>
        <%= link_to 'Contact', contact_path %>
    <% end %>
    
    <% if current_page?(controller: 'static_pages', action: 'help') %>
        <%= link_to 'Home', root_path %>
        <%= link_to 'About', about_path %>
        <%= link_to 'Help', help_path, class: 'active' %>
        <%= link_to 'Contact', contact_path %>
    <% end %>
    
    <% if current_page?(controller: 'static_pages', action: 'contact') %>
        <%= link_to 'Home', root_path %>
        <%= link_to 'About', about_path %>
        <%= link_to 'Help', help_path %>
        <%= link_to 'Contact', contact_path, class: 'active' %>
    <% end %>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <style>@import url('https://fonts.googleapis.com/css?family=Cinzel+Decorative|Ruslan+Display|Source+Code+Pro|Syncopate');</style>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>
    About SocialH3x
</h1>

<p>
    SocialH3x is aiming to provide you with the ultimate social media experience!
    From using top-of-the-line security protocols, and ensuring the server & application 
    security measures. We are aiming to bring forth the next generation of social media experience.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact SocialH3x</h1>

<p>
    If you have any questions or concners, please feel free to contact us directly;<br/>
    <br/>
    
    Ruby on Rails Engineer | Linux Server Admin ~ <%= link_to 'aubrey@socialhex.org', 'mailto:aubrey@socialhex.org' %><br/>
    <br/>
    Marketing & Promoting ~ <%= link_to 'kurt@socialhex.org', 'mailto:kurt@socialhex.org' %><br/>
    <br/>
    Artist ~ <%= link_to 'adam@socialhex.org', 'mailto:adam@socialhex.org' %>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>
    Help with SocialH3x 
</h1>

<p>
    If you would like assistance on using your new SocialH3x account, please 
    watch this video;<br/>
    ** Insert YouTube Video Here! **
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
    <h1> Welcome to SocialH3x</h1>
    
    <h2>
        This is the landing page for your ultimate, safe, and secured 
        social media site <%= link_to 'SocialH3x', root_path %>!
    </h2>
    
    <%= link_to 'Register Now!', '#', class: 'btn btn-lg btn-primary' %>
</div>